import type { NextPage } from "next";
import Head from "next/head";
import { animeUrl } from "../config/baseUrl";
import DailyAnime from "../components/Update/DailyAnime";
import { DailyAnimeProps } from "../components/Update/type";
import { Box } from "@chakra-ui/react";
import useScreenSize from "../components/hook/useScreenSize";

const Home: NextPage<{ dailyAnime: DailyAnimeProps[] }> = ({ dailyAnime }) => {
  const { width, height } = useScreenSize();
  return (
    <Box w={"100%"} h={height - 60} overflow={"auto"}>
      <Head>
        <title>还没想好的网站名</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box w={[width, "100%"]}>
        {dailyAnime.map((item, index) => (
          <DailyAnime key={index} {...item} />
        ))}
      </Box>
    </Box>
  );
};

export const getStaticProps = async () => {
  const res = await fetch(`${animeUrl}/anime/bangumi/updates`);
  const dailyAnime = await res.json();

  return {
    props: {
      dailyAnime,
    },
  };
};

export default Home;
